import type { NextPage } from "next";
import Head from "next/head";
import { styled } from "styles/stitches.config";
import type * as Stitches from "@stitches/react";
import tw from "twin.macro";

const Button = styled("button", {
    ...tw`text-body`,
    fontFamily: "$display",
    background: "$primary",
    display: "block",
    color: "white",
    padding: "$3xs",
    margin: 32,
    borderRadius: "$md",
});

const TypeTester = styled("div", {
    ...tw`leading-tight whitespace-nowrap`,
    variants: {
        size: {
            "-2": {
                fontSize: "$-2",
            },
            "-1": {
                fontSize: "$-1",
            },
            "0": {
                fontSize: "$0",
            },
            "1": {
                fontSize: "$1",
                fontFamily: "$display",
            },
            "2": {
                fontSize: "$2",
                fontFamily: "$display",
            },
            "3": {
                fontSize: "$3",
                fontFamily: "$display",
            },
            "4": {
                fontSize: "$4",
                fontFamily: "$display",
            },
            "5": {
                fontSize: "$5",
                fontFamily: "$displayLarge",
            },
            "6": {
                fontSize: "$6",
                fontFamily: "$displayLarge",
            },
            "7": {
                fontSize: "$7",
                fontFamily: "$displayLarge",
            },
        },
    },
});

const Tokens: NextPage = () => {
    const TypeSizes = ["-2", "-1", "0", "1", "2", "3", "4", "5", "6", "7"];
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Button>Jackdaws, bitch</Button>
                <div>
                    {TypeSizes.map((typeSize: any, i) => {
                        return (
                            <TypeTester size={typeSize} key={i}>
                                Jackdaws love my big sphinx of quartz
                            </TypeTester>
                        );
                    })}
                </div>
            </main>
        </div>
    );
};

export default Tokens;
