import type { NextPage } from "next";
import Head from "next/head";
import { styled } from "../styles/stitches.config";

const Button = styled("button", {
    background: "$primary",
});

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                sadasdasd <Button>Hello</Button>
            </main>
        </div>
    );
};

export default Home;
